title: Jorge de la Torre - DevOps & Cloud Security Engineer
email: jorgedlt@gmail.com
description: >-
  Senior DevOps & Cloud Security Engineer specializing in secure infrastructure, automation, and compliance across Azure, AWS, GCP, and IBM Cloud.
  Expertise in IaC, CI/CD pipelines, monitoring, and cybersecurity for resilient cloud solutions.
baseurl: ""
url: "https://jorgedlt.github.io"
github_username: jorgedlt
linkedin_url: "https://www.linkedin.com/in/jorge-de-la-torre-6668b772/"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed